

---
apiVersion: v1
kind: Service
metadata:
  name: fb-cip-svc
  labels:
    app: fb-app
    env: prod
spec:
  type: ClusterIP
  selector:
     app: fb-app
     env: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080